### ISSUE TITLE
[bat] Make local address optional as soon as dispatcher allows nil local addresses

### ISSUE THREAD

**Issue by chaehni** [netsec-ethz/scion-apps#11]
Currently, dispatcher doesn't allow nil local addresses. This is very inconvenient for a tool like bat that exists for quickly sending requests to a web server. As soon as dispatcher allows nil addresses get rid of the '-l' flag and let dispatcher choose address/port. This requires shttp to change as well. https://github.com/netsec-ethz/scion-apps/issues/8

In the meantime integrate a mechanism to infer the local address.

**Comment by chaehni** [comment]
https://github.com/netsec-ethz/scion-apps/pull/55 makes it possible to omit the local address by passing a `localhost` address by default.

**Comment by matzf** [comment]
Done as part of refactoring of the libraries.
