### ISSUE TITLE
Create CODEOWNERS file

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scion-apps#112]
As a developer I'd like to be able to easily trace owner/author/responsible for different parts of the codebase. In order to achieve this, I'd like `CODEOWNERS` file to exists in the root directory of the repo following the standard defined in

- https://docs.gitlab.com/ee/user/project/code_owners.html
- https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

A very easy to digest example is available at https://tech.people-doc.com/using-github-codeowners-file.html

**Comment by matzf** [comment]
Not really applicable (anymore?) as nobody really has a great sense of ownership over this and it's just us devs at netsec feeling somewhat responsible for all of this stuff here.
