### ISSUE TITLE
bwtestclient pointing to old scion config when omitting -c option

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-apps#113]
when using scion-bwtestclient without -c option, bwtestclient tries to access the scion config from the old location:

`CRIT[10-27|14:56:47] Fatal error. Exiting.                    err="open /home/scion/go/src/github.com/scionproto/scion/gen/ia: no such file or directory"`

**Comment by matzf** [comment]
This is another incarnation of #89. Closed as duplicate.
