### ISSUE TITLE
[appquic] ListenPort does not time out/return an error

### ISSUE THREAD

**Issue by mmalesev** [netsec-ethz/scion-apps#131]
The following function in appquic does not time out or return an error even though SCION_DAEMON_ADDRESS points to a wrong sciond address.
`func ListenPort(port uint16, tlsConf *tls.Config, quicConfig *quic.Config) (quic.Listener, error)`

For example, if you run the current version of scionlab and set SCION_DAEMON_ADDRESS=127.0.0.1:30455 (sciond for the metrics purposes), the function will simply never return.

**Comment by matzf** [comment]
This was fixed in #135
