### ISSUE TITLE
Wrong build targets

### ISSUE THREAD

**Issue by FR4NK-W** [netsec-ethz/scion-apps#144]
The current build targets are in my opinion wrong:

The macro build targets build multiple binaries with the same name (server, client), which then overwrite each other when installed.

The build targets should build binaries with the same names as those used by the packaged version.

The current https://github.com/netsec-ethz/scion-apps/blob/cc4e1dc18ebaf340cd3d32e381e6900f0879ae0a/Makefile#L33 way made it easy to have something that covered all apps, but is also confusing and does not work for the current state, diverge from the scion-apps build as part of the packages.

**Comment by matzf** [comment]
Agreed. We should also build to a common `bin/` directory at the project root. I'd propose to just get rid of the macro magic and have a simple (albeit lengthy) Makefile:
```Makefile
scion-netcat:
   go build -o $(BIN)/$@ /netcat
scion-ssh: 
   go build -o $(BIN)/$@ ./ssh/client
scion-sshd:
   go build -o $(BIN)/$@ ./ssh/server
scion-bwtestclient:
   go build -o $(BIN)/$@ ./bwtester/bwtestclient/
scion-bwtestserver:
   go build -o $(BIN)/$@ ./bwtester/bwtestserver/
helloworld:
   go build -o $(BIN)/$@ ./_examples/helloworld/
...
```
