### ISSUE TITLE
The packaged version of `paparazzi` is missing dependencies

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-apps#159]
When running `scion-paparazzi` (installed as an Ubuntu package), I receive the error
```
Traceback (most recent call last):
  File "/usr/bin/scion-paparazzi", line 3, in <module>
    from picamera import PiCamera, Color
ModuleNotFoundError: No module named 'picamera'
```

**Comment by juagargi** [comment]
There is no `picamera` deb package available that I can find, and installing it with `pip` seems to fail when checking if the system is a Raspberry Pi. I suggest to `try except` the import and print a message instead of attempting to install the dependencies in our `paparazzi` package.

**Comment by juagargi** [comment]
PR #160 doing just that ^^.
Other alternative would be to just leave it as is.

**Comment by matzf** [comment]
Discussion in #160 concluded with wontfix.
