### ISSUE TITLE
[shttp] Feature Request: Support full SCION address in http.Request.Host field

### ISSUE THREAD

**Issue by baehless** [netsec-ethz/scion-apps#17]
The standard Golang http client resolves IP addresses in the request's host field (with the form `host:port`), it would be nice if shttp could support this as well. E.g. it should be possible to make a request to `https://17-ffaa:0:1102,[192.33.93.166]:33333/foo/bar`.
Then it would be possible resolve http requests without using domain names but just the SCION address, partially solving #10 before RAINS is introduced and simplifying the implementation of 2SMS, where domain names are not used.

**Comment by matzf** [comment]
See also #16; not a fix complete for this as far as I understand, but relevant anyway.

**Comment by chaehni** [comment]
Yes, this is currently not supported. Mainly because we use the standard `net/http` client which doesn't know how to parse SCION addresses. We would need to have our own `shttp` client implementation to do that.

**Comment by baehless** [comment]
I see, thanks for the explanation.

**Comment by chaehni** [comment]
closed by https://github.com/netsec-ethz/scion-apps/pull/59
