### ISSUE TITLE
[bwtester]Does the packet created automatically by the system?

### ISSUE THREAD

**Issue by Memtwo** [netsec-ethz/scion-apps#175]
In bwtester, does the packet created automatically by the system?
Is there any way to create my own packets and inject them?

**Comment by matzf** [comment]
Yes, the payload packet data for the bandwidth probing traffic is generated on the fly by the bandwidth tester. It generates a pseudo-random byte sequence with a seed/key shared during the client/server handshake.

Currently, there is no way to let the bandwidth tester send custom data, like it is e.g. possible with iperf. This would be a welcome addition, though.
Please note that we're aware that this bwtester is a bit clunky. Adding such a feature would probably warrant a significant (and also welcome) rewrite.

**Comment by Memtwo** [comment]
> Yes, the payload packet data for the bandwidth probing traffic is generated on the fly by the bandwidth tester. It generates a pseudo-random byte sequence with a seed/key shared during the client/server handshake.
> 
> Currently, there is no way to let the bandwidth tester send custom data, like it is possible e.g. with iperf. This would be a welcome addition, though.
> Please note that we're aware that this bwtester is a bit clunky. Adding such a feature would probably warrant a significant (and also welcome) rewrite.

thanks!
