### ISSUE TITLE
quic-go library prints a warning about receive buffer size

### ISSUE THREAD

**Issue by joelwanner** [netsec-ethz/scion-apps#201]
Thanks @matzf for the changes in 08ad6182351e3fa33f67869a18818f0022cf70f1, they are actually very helpful for implementing the ISL course.

I noticed that when I use the `shttp` package, the `quic-go` dependency is complaining about not being able to set the receive buffer size.

This is not critical, as the HTTP operations still work, but I'm trying to avoid irritating users that would see this message.

# Steps to reproduce

```
make example-shttp-client
./bin/example-shttp-client -s 17-ffaa:0:1107,1.2.3.4
```
(no server needed to be running there, it's just a dummy address)

# Output

```
2021/10/01 15:30:07 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```

# Additional information
 
The problem seems to be [at this call](https://github.com/lucas-clemente/quic-go/blob/master/packet_handler_map.go#L85).

**Comment by joelwanner** [comment]
Let me know if there is an easy fix that I can help implement. Unfortunately, I haven't managed to squelch the message, as it's output via the default logger from the `log` package.

**Comment by matzf** [comment]
Thanks for reporting this @joelwanner; I had noticed this before, but never took the time to see how we can shut this up.

**Comment by joelwanner** [comment]
Looks good, thanks for the quick fix!
