### ISSUE TITLE
Bump Versions

### ISSUE THREAD

**Issue by leonrinkel** [netsec-ethz/scion-apps#239]
go1.16 is pretty old now and also other dependencies are out of date or even deprecated. This makes it difficult to use the pan library in other up-to-date projects.

Biggest roadblocks for me are:
- github.com/lucas-clemente/quic-go has become github.com/quic-go/quic-go
- github.com/netsec-ethz/scion uses a pretty old grpc
- inet.af/netaddr is deprecated and breaks with newer Go versions

**Comment by marcfrei** [comment]
With the already merged PRs mentioned above and with https://github.com/netsec-ethz/scion-apps/pull/246 we are now pretty much up to date again.
