### ISSUE TITLE
Bump scionproto/scion version

### ISSUE THREAD

**Issue by martenwallewein** [netsec-ethz/scion-apps#244]
Hey guys, 

in scope of the work on IPFS over SCION we thought about trying to bump the scionproto/scion dependency to one of the newest versions, to be up-to-date with recent changes, but also for having other dependencies (like quic-go, grpc, etc) on newer versions. Does anyone see a strong reason against moving scion-apps to a newer scionproto/scion version? If not, I would give it a try.

Cheers,
Marten

**Comment by marcfrei** [comment]
Sounds good to me in principle. One potential problem I see though, is that newer versions of scionproto implement the new DRKey design whereas in SCIONLab we still have an older DRKey version deployed. So this would probably lead to a situation where scion-apps are not entirely compatible with SCIONLab anymore. At least until we upgrade the SCIONLab deployment to the newest scionproto version too which is planned for later this year.

**Comment by martenwallewein** [comment]
Hey Marc, thanks for the reply! That sounds quite critical for me. Would you suggest to wait for the upgrade of SCIONLab to the newest scionproto?

**Comment by marcfrei** [comment]
Or we could maybe also do the update now but keep it in a separate branch until SCIONLab is updated. Would that work for your IPFS use-case?

**Comment by JordiSubira** [comment]
Hello guys, I think @marcfrei idea sounds good. It shouldn't take to much effort to maintain both until scionlab upgrades to the newest verson, since there aren't any scion-apps at the moment using DRKey. Hopefully, this gets resolved before those application emerged.

**Comment by martenwallewein** [comment]
Sounds good to me. Yeah I think for now this is fine. Will come up with a PR as soon as I find time to tackle this. Thanks for your comments!

**Comment by martenwallewein** [comment]
I managed to get started with this. 

Updates and migrations of imports are already done, now working on handling breaking changes in scionproto. Code is here: https://github.com/martenwallewein/scion-apps/tree/bump/scionproto

Also waits for this one: https://github.com/netsec-ethz/rains/pull/242
