### ISSUE TITLE
bat - error looking for SCION dispatcher socket

### ISSUE THREAD

**Issue by thomasgruebl** [netsec-ethz/scion-apps#257]
Hi,

I've successfully set up and configured two SCION ASes, and I can ping them, exchange sensor data using the scion-sensorfetcher, and I can test the bandwidth with the scion-bwtestclient. However, scion-bat does not seem to work properly. Whenever I try to get data from my server using the following command:

`scion-bat https://<my_other_AS>,127.0.0.1/home`

I get an error saying:

![Screenshot 2024-09-22 at 17 34 22](https://github.com/user-attachments/assets/32a276dc-ce1e-4d18-82ef-5a8e33e1b217)

The local directory /run/shm/dispatcher does indeed not exist. Do you know if I'm missing a configuration step?

All scion services are running properly:

![Screenshot 2024-09-22 at 17 28 13](https://github.com/user-attachments/assets/93e4bdd4-02fa-440e-8c3a-9fbef5d01d16)

Thanks for your help!

Best,

Thomas

**Comment by JordiSubira** [comment]
Hello Thomas, it seems that you are running an old version of the  `scion-bat` binary. In principle, the latest version should work with the new scionlab binaries.

$ sudo apt show scion-apps-bat
Package: scion-apps-bat
Version: 3.5.2
Built-Using: Bazel
Priority: optional
Section: net
Maintainer: ETH Zurich, SCIONLab Team <scionlab-admins@sympa.ethz.ch>
Installed-Size: unknown
Depends: scion-daemon, scion-dispatcher
Homepage: https://www.scion-architecture.net
Download-Size: 28.6 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.netsec.inf.ethz.ch/debian all/main amd64 Packages
Description: SCION/QUIC-enabled fork of bat, which is a curl-like tool
 for interacting with webservers
```

You can run
```
sudo apt-get update
sudo apt install scion-apps-*
```

**Comment by thomasgruebl** [comment]
Hi,

thanks for your swift response. I have tried that but it didn't work.

Also, I'm on arm64 and apparently the latest version that I can pull for arm64 is 3.5.1 and not 3.5.2.

Do you think this could be an issue?

`Package: scion-apps-bat
Version: 3.5.1
Built-Using: Bazel
Priority: optional
Section: net
Maintainer: ETH Zurich, SCIONLab Team <scionlab-admins@sympa.ethz.ch>
Installed-Size: unknown
Depends: scion-daemon, scion-dispatcher
Homepage: https://www.scion-architecture.net
Download-Size: 21.6 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.netsec.inf.ethz.ch/debian all/main arm64 Packages
Description: SCION/QUIC-enabled fork of bat, which is a curl-like tool
 for interacting with webservers
`

Thanks,

Thomas

**Comment by JordiSubira** [comment]
Hello,

At least I would expect you have some other problem with that version, but not the one you were seeing here



> Hi,
> 
> I've successfully set up and configured two SCION ASes, and I can ping them, exchange sensor data using the scion-sensorfetcher, and I can test the bandwidth with the scion-bwtestclient. However, scion-bat does not seem to work properly. Whenever I try to get data from my server using the following command:
> 
> `scion-bat https://<my_other_AS>,127.0.0.1/home`
> 
> I get an error saying:
> 
> ![Screenshot 2024-09-22 at 17 34 22](https://private-user-images.githubusercontent.com/60517996/369699254-32a276dc-ce1e-4d18-82ef-5a8e33e1b217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQ3ODUsIm5iZiI6MTcyNzE2NDQ4NSwicGF0aCI6Ii82MDUxNzk5Ni8zNjk2OTkyNTQtMzJhMjc2ZGMtY2UxZS00ZDE4LTgyZWYtNWE4ZTMzZTFiMjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYzk1MTJkNjEwNTBjNzdkNTlhYWNlYjIyZjJmMGU1NTkzOWI4YzY0ZTgzNTY3MzRhNGMwMmJhNTliYWMxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p3YJezQB5JACEpIE2lO993ifyVdcjpctCNsZGfOCuok)
> 
> The local directory /run/shm/dispatcher does indeed not exist. Do you know if I'm missing a configuration step?
> 
> All scion services are running properly:
> 
> ![Screenshot 2024-09-22 at 17 28 13](https://private-user-images.githubusercontent.com/60517996/369699694-93e4bdd4-02fa-440e-8c3a-9fbef5d01d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjQ3ODUsIm5iZiI6MTcyNzE2NDQ4NSwicGF0aCI6Ii82MDUxNzk5Ni8zNjk2OTk2OTQtOTNlNGJkZDQtMDJmYS00NDBlLThjM2EtOWZiZWY1ZDAxZDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDIyZjhjYWRkMTY1ZjQxMzkwNmZlMGE5MzJhYmQ1ZDMxZGVkZTE5ZTU0ZDk1MmZkZDNhNTUyY2JhYTdkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zqMyURs9xIwQ5YttE-HMZoS7PdGKiNyA7QfFQb7w6CE)
> 
> Thanks for your help!
> 
> Best,
> 
> Thomas

For more interactive feedeback, we can use our Elements public room for SCION developers. https://matrix.to/#/#dev:matrix.scion.org. Feel free to follow-up there.

**Comment by JordiSubira** [comment]
We updated version 3.5.2 also for arm64 which solves the issue.
