### ISSUE TITLE
Port bat app to SCIONLab nextversion

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-apps#30]
The SCIONLab update is coming. We need to port all existing SCION applications so they build and run with the next version.
Typically you will need to register and get a user AS from the testing coordinator at
http://http://scionlabtestbed.inf.ethz.ch:8080
And use it to run and test the application you are trying to port.
Another possibility is, of course, to install the next version in your local machine. Just check out the `scionlab_nextversion` branch from our repository, and build it following the standard procedure.

This issue deals with porting `bat`. It depends on issue #29

**Comment by chaehni** [comment]
Closed by 87c9760d4863e225f358617c983bca9e67e687f7
