### ISSUE TITLE
[shttp] Connection closed after IdleTimeout but client not aware of that

### ISSUE THREAD

**Issue by baehless** [netsec-ethz/scion-apps#43]
### Setup Description
We have a server and a client as in the examples with the only difference that the client will regularly (e.g. every minute) do requests to the server instead of just once. 

### Problem description
If the request period is higher than 29-30 seconds, then the server will close the connection because QUIC default **idle timeout** is 30 seconds. But on the client side this won't be noticed and will thus result in the client attempting to reuse the closed connection and then returning **NetworkIdleTimeout: No recent network activity**.

### Suggestions
I see two possibilities:
1. Allow specifying a different **IdleTimeout** in the server (https://godoc.org/github.com/lucas-clemente/quic-go)
1. Improve connection management in the client so that if the server closes the connection a new one will be established

**Comment by chaehni** [comment]
The client can pass a `quic.Config` to the Transport. Specifically you can set the `KeepAlive` flag or set a different `NetworkIdleTimeout`.

**Comment by baehless** [comment]
So you would suggest doing something like the following?
```
scionClient := &http.Client{
	Transport: &shttp.Transport{
		LAddr: localAddress,
                rt:h2quic.RoundTripper{QuicConfig{IdleTimeout: 65 * time.Second()}}
	},
}
```
In such case I see a few problems, in primis the fact that `rt` is private and cannot be accessed when creating the trasport.

**Comment by chaehni** [comment]
I just checked the code and realised that something must have gone wrong when merging https://github.com/netsec-ethz/scion-apps/pull/16.
The Transport is supposed to expose a puplic `quic.Config` which is passed to the underlying connection.
More specifically, it is configured to keep connections alive by default.
This piece of code went missing.

**Comment by chaehni** [comment]
fixed by https://github.com/netsec-ethz/scion-apps/pull/45
