### ISSUE TITLE
govendor list +o returns non-empty

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-apps#57]
When running `govendor list +o` on current master, it returns some missing libraries:
```
  m github.com/jtolds/gls                            
  m github.com/smartystreets/assertions              
  m golang.org/x/image/font                          
  m golang.org/x/image/font/basicfont                
  m golang.org/x/image/math/fixed                    
  m roughtime.googlesource.com/go/client/monotime    
  m roughtime.googlesource.com/go/config             
  m roughtime.googlesource.com/go/protocol
```
Some of them come from our `roughtime` app, but I don't know if all of them do. 
Find out why we have these missing libraries and modify consequently our `vendor.json`

**Comment by mwfarb** [comment]
I can speak for the `golang.org/x/image` libs. They are for test image servers for webapp. I can supply the proper versions

**Comment by mwfarb** [comment]
Patch attached.
[add-imgserver-test-vendor-libs.patch.txt](https://github.com/netsec-ethz/scion-apps/files/3039338/add-imgserver-test-vendor-libs.patch.txt)

**Comment by chaehni** [comment]
I don't really trust this `govendor` tool on that. For example, `govendor list +u` shows a couple packages which are apparently unused. However, removing them with `govendor remove +u` and then trying to compile the apps fails because of missing dependencies.

**Comment by juagargi** [comment]
The entries regarding roughtime were real. I have created PR #60 fixing roughtime (this vendor plus other small things). After that PR we only have this `govendor list +o` :
```
  m github.com/jtolds/gls                  
  m github.com/smartystreets/assertions    
```
We have to decide if we ignore them and close this PR, or do something.

**Comment by juagargi** [comment]
The latest commits in PR #60 solve this issue. Now `govendor list +o` is empty.
