### ISSUE TITLE
[webapp] Move GAE API Keys tool to this repo

### ISSUE THREAD

**Issue by mwfarb** [netsec-ethz/scion-apps#58]
This should move to https://github.com/netsec-ethz/scion-apps for future maintenance: https://github.com/netsec-ethz/scion-viz/tree/master/python/appengine.

Also, `webapp/config/servers_default.json` could move to the GAE tool in some form to allow for more flexible updates in the future (suggested in https://github.com/netsec-ethz/scion-apps/pull/44).

**Comment by matzf** [comment]
As discussed in the related PR #146; we'll rather integrate this with the scionlab coordinator directly, see netsec-ethz/scionlab#284.
