### ISSUE TITLE
webapp not working on VM

### ISSUE THREAD

**Issue by the4daspect** [netsec-ethz/scion-apps#66]
`ubuntu@ubuntu-xenial:~/go/src/github.com/netsec-ethz/scion-apps/webapp$ webapp -a 0.0.0.0 -p 8080 -r .`
Output: `webapp: command not found`

**Comment by mwfarb** [comment]
As more information, did the build process from https://github.com/netsec-ethz/scion-apps/blob/master/README.md output any errors?
```
./deps.sh
make
```

**Comment by the4daspect** [comment]
It works now. There was some issue with installation of dependencies. 
However, camera app still doesn't work.

`2019-05-13 15:51:07.768819+0000 [INFO] t=2019-05-13T15:51:07+0000 lvl=dbug msg="Registered with dispatcher" addr="17-ffaa:1:c28,[10.0.2.15]:30001 (UDP)"
2019/05/13 15:51:19 Error: could not obtain file information`

**Comment by the4daspect** [comment]
Now, when I switched to Local topology, none of the apps are working for me.
`./deps.sh `
works fine!
However, make results in error
`make: Nothing to be done for 'all'.`
and make install in error
`make: *** No rule to make target 'install'.  Stop.`

when I try to open sensor app/webapp: it simply outputs command not found.
