### ISSUE TITLE
[shttp] Make specifying local address optional

### ISSUE THREAD

**Issue by chaehni** [netsec-ethz/scion-apps#8]
Currently, the SCION dispatcher requires clients to explicitly set their local SCION address. This is unconvenient.
As soon as dispatcher allows for nil local addresses get rid of mandatory LAddr field in RoundTripper and make it optional instead.
As an option still allow clients to specify the address (or port only).

**Comment by chaehni** [comment]
As of 0b3c575341685a8fda9ef627b5c263b21ebee0f7 local SCION addresses are optional for apps and resolved by parsing `/etc/hosts` or parsing `/gen/ia`.

**Comment by matzf** [comment]
This has been done, as part of refactoring the libraries.
