### ISSUE TITLE
make install: compilation terminated

### ISSUE THREAD

**Issue by the4daspect** [netsec-ethz/scion-apps#85]
```
# github.com/netsec-ethz/scion-apps/vendor/github.com/msteinert/pam
../../vendor/github.com/msteinert/pam/transaction.go:4:31: fatal error: security/pam_appl.h: No such file or directory
 //#include <security/pam_appl.h>
                               ^
compilation terminated.
Makefile:24: recipe for target 'ssh/server/server' failed
make: *** [ssh/server/server] Error 2
```

**Comment by juagargi** [comment]
That seems to be the behavior without the `libpam0g-dev` library. On the ssh README 
https://github.com/netsec-ethz/scion-apps/blob/master/ssh/README.md

we read that we need said library to build ssh. As this repository becomes larger we might decide to split the tools in several projects, but for now we build them all at once.
Please try out the solution in the ssh README and let us know.

**Comment by mwfarb** [comment]
@the4daspect Does https://github.com/netsec-ethz/scion-apps/pull/86 resolve this for you?
