### ISSUE TITLE
[sensorfetcher] Too strong assumption about $SC env variable

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scion-apps#88]
Currently the `sensorfetcher` app assumes existence of the `$SC` env variable pointing to the directory containing `/gen/ia`. This means it must always be run from the context of `scion` user, what in the scope of automated infrastructure monitoring is not desired.

If access to `/gen/ia` is required, the app should be able to consume it e.g. as a command line parameter, but not assume the `$SC` env variable will be present.

**Comment by chaehni** [comment]
Please see the answer to https://github.com/netsec-ethz/scion-apps/issues/89

**Comment by juagargi** [comment]
Closing this as #89 applies now to `sensorfetcher` as well
