### ISSUE TITLE
[lib] integrate RAINS domain name resolution

### ISSUE THREAD

**Issue by chaehni** [netsec-ethz/scion-apps#9]
When RAINS is ready, make the `Dial()` method resolve hostnames using RAINS istead of using the custom `DNS` field in the `Transport`.

**Comment by chaehni** [comment]
Since 87c9760d4863e225f358617c983bca9e67e687f7 the `DNS` field was replaced by a hostname resolution based on parsing the `etc/hosts` file.
RAINS is not yet integrated.

**Comment by matzf** [comment]
In the meantime, this has been done.
