### ISSUE TITLE
[imagefetcher] No deterministic output location

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scion-apps#90]
Currently the `imagefetcher` app will save the output image in the directory where it's run from with the name returned by the server. This means from the user perspective the output filename is never deterministic.

In the scope of automated infrastructure monitoring it must be strictly possible to set an arbitrary output filename where the image will be saved, similarly to e.g. `wget -O`

**Comment by chaehni** [comment]
Fixed by https://github.com/netsec-ethz/scion-apps/pull/94
