### ISSUE TITLE
[bwserver] Multi-client handling does not scale

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scion-apps#91]
Currently it seems the `bwserver` is not handling properly more than ~5 clients trying to perform the test at the same time.

Please note this is a very draft bug report without much reliable data. It is based only on the experiment of trying to run 50 instances of `bwclient` which failed very fast.

If someone decides to jump on it, more specific data can be regenerated and provided.

**Comment by matzf** [comment]
If I'm interpreting this correctly, the `bwserver` is actually designed to only handle _one_ client at a time:
https://github.com/netsec-ethz/scion-apps/blob/850e1e3be287912dc324573c872f1362dfe82f15/bwtester/bwtestserver/bwtestserver.go#L199-L231

If it handles 5, then it's not working correctly ;)

**Comment by matzf** [comment]
As described above, bwtester intentionally handles only one client at a time.
